# Generated by Django 5.0 on 2023-12-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0003_like_content_type_like_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsaboutsite',
            name='like',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
