# Generated by Django 5.0 on 2023-12-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0005_createnewradit_title_alter_createnewradit_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='createnewradit',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
