# Generated by Django 5.0 on 2023-12-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0007_commentdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdetail',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
