# Generated by Django 5.0 on 2023-12-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0009_remove_commentdetail_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createnewradit',
            old_name='slug',
            new_name='post_slug',
        ),
    ]
