# Generated by Django 5.0 on 2023-12-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0010_rename_slug_createnewradit_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentdetail',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='createnewradit',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
