# Generated by Django 5.0 on 2023-12-13 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0011_commentdetail_slug_alter_createnewradit_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentdetail',
            name='slug',
        ),
    ]
