# Generated by Django 5.0 on 2023-12-14 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0012_remove_commentdetail_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentdetail',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_details', to='mainPageApp.createnewradit'),
        ),
    ]
