# Generated by Django 5.0 on 2023-12-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0015_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ava',
            field=models.ImageField(upload_to='avatars/'),
        ),
    ]
