# Generated by Django 5.0 on 2023-12-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainPageApp', '0017_rename_ava_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentdetail',
            options={'verbose_name': 'Детали комментариев', 'verbose_name_plural': 'Детали комментариев'},
        ),
        migrations.AlterModelOptions(
            name='createnewradit',
            options={'verbose_name': 'Создать новый редит', 'verbose_name_plural': 'Создать новый редит'},
        ),
        migrations.AlterModelOptions(
            name='reviewsaboutsite',
            options={'verbose_name': 'Комменты о сайте', 'verbose_name_plural': 'Комменты о сайте'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профиль пользователя'},
        ),
    ]
